language: c
compiler:
  - gcc
os: linux
dist: bionic

install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - make test

script:
  - LD_LIBRARY_PATH=./test ./test/test

after_success:
  - lcov --rc lcov_branch_coverage=1 -c -i -d ./test -o .coverage.base
  - lcov --rc lcov_branch_coverage=1 -c -d ./test -o .coverage.run
  - lcov --rc lcov_branch_coverage=1 -d ./test -a .coverage.base -a .coverage.run -o .coverage.total
  - coveralls-lcov .coverage.total

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - nnminh171298@gmail.com
    on_success: always
    on_failure: change
