language: cpp
compiler:
  - gcc
os: linux
dist: bionic

addons:
  apt:
    packages:
      - doxygen

install:
  - sudo apt-get install -y lcov
  - sudo apt-get install -y libbluetooth-dev
  - sudo apt-get install -y libjsoncpp-dev
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y libssl-dev
  - gem install coveralls-lcov

before_script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - env | grep -i 'CC='
  - env | grep -i 'CXX='
  - make test

script:
  - doxygen Doxyfile
  - LD_LIBRARY_PATH=./test ./test/test

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

after_success:
  - lcov --rc lcov_branch_coverage=1 -c -i -d ./test -o .coverage.base
  - lcov --rc lcov_branch_coverage=1 -c -d ./test -o .coverage.run
  - lcov --rc lcov_branch_coverage=1 -d ./test -a .coverage.base -a .coverage.run -o .coverage.total
  - coveralls-lcov .coverage.total

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - nomi2208.ci@gmail.com
    on_success: always
    on_failure: change
